# Generated by Django 3.0.6 on 2020-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
