# Generated by Django 3.0.6 on 2020-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogapp',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
